name: store_launcher_plus
description: StoreLauncher is a powerful utility package for Flutter applications that allows developers to seamlessly launch the Google Play Store and Apple App Store directly from their apps.
version: 1.0.3
repository: https://github.com/ayushsingh363/store_launcher_flutter

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
