name: store_launcher_plus
description: App Store/Play Store launcher for android and ios apps
version: 1.0.2
repository: https://github.com/ayushsingh363/store_launcher_flutter

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
