name: store_launcher
description: App Store/Play Store launcher for android and ios apps
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
